AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31
Description: AWS Cost Alert System (SAM)

Parameters:
  ProjectName:
    Type: String
    Default: aws-cost-alerts
    Description: Base name used for resources.
  ScheduleExpression:
    Type: String
    Default: cron(0 8 * * ? *)
    Description: EventBridge schedule (defaults to 08:00 UTC daily).
  SenderEmail:
    Type: String
    Default: ''
    Description: SES-verified sender email (required for SES).
  RecipientEmails:
    Type: String
    Default: ''
    Description: Comma-separated recipient emails.
  ArchiveEnabled:
    Type: String
    Default: 'true'
    AllowedValues:
      - 'true'
      - 'false'
    Description: Enable S3 archival of daily JSON snapshots.
  ArchiveRetentionDays:
    Type: Number
    Default: 30
    Description: Days to retain archived data in S3.
  BudgetParameterName:
    Type: String
    Default: /aws-cost-alerts/budget-amount
    Description: SSM Parameter name holding the monthly budget amount.
  TopServicesCount:
    Type: Number
    Default: 10
    Description: Number of top services to include in the breakdown.

Conditions:
  UseArchive: !Equals [!Ref ArchiveEnabled, 'true']

Globals:
  Function:
    Runtime: python3.14
    Timeout: 60
    MemorySize: 1024
    Tracing: Active
    Environment:
      Variables:
        PROJECT_NAME: !Ref ProjectName
        SENDER_EMAIL: !Ref SenderEmail
        RECIPIENT_EMAILS: !Ref RecipientEmails
        ARCHIVE_ENABLED: !Ref ArchiveEnabled
        ARCHIVE_BUCKET: !If [UseArchive, !Ref ArchiveBucket, '']
        ARCHIVE_RETENTION_DAYS: !Ref ArchiveRetentionDays
        BUDGET_PARAM_NAME: !Ref BudgetParameterName
        TOP_SERVICES_COUNT: !Ref TopServicesCount

Resources:
  CostAlertFunction:
    Type: AWS::Serverless::Function
    Properties:
      FunctionName: !Sub '${ProjectName}-daily'
      CodeUri: src/
      Handler: handler.lambda_handler
      Policies:
        - AWSLambdaBasicExecutionRole
        - Statement:
            - Sid: CostExplorerRead
              Effect: Allow
              Action:
                - ce:GetCostAndUsage
                - ce:GetCostForecast
                - ce:GetDimensionValues
              Resource: '*'
            - Sid: ParameterRead
              Effect: Allow
              Action:
                - ssm:GetParameter
              Resource: '*'
            - Sid: CloudWatchMetrics
              Effect: Allow
              Action:
                - cloudwatch:PutMetricData
              Resource: '*'
            - Sid: SendSesEmail
              Effect: Allow
              Action:
                - ses:SendEmail
                - ses:SendRawEmail
              Resource: '*'
            - !If
              - UseArchive
              - Sid: ArchiveWrite
                Effect: Allow
                Action:
                  - s3:PutObject
                  - s3:GetObject
                Resource:
                  - !Sub 'arn:${AWS::Partition}:s3:::${ArchiveBucket}/*'
              - !Ref AWS::NoValue
      Events:
        DailySchedule:
          Type: Schedule
          Properties:
            Schedule: !Ref ScheduleExpression
            Name: !Sub '${ProjectName}-daily-schedule'
            Description: Daily AWS cost alert schedule
            Enabled: true

  ArchiveBucket:
    Type: AWS::S3::Bucket
    Condition: UseArchive
    DeletionPolicy: Retain
    UpdateReplacePolicy: Retain
    Properties:
      LifecycleConfiguration:
        Rules:
          - Id: ExpireCostAlerts
            Status: Enabled
            ExpirationInDays: !Ref ArchiveRetentionDays
      BucketEncryption:
        ServerSideEncryptionConfiguration:
          - ServerSideEncryptionByDefault:
              SSEAlgorithm: AES256
      PublicAccessBlockConfiguration:
        BlockPublicAcls: true
        BlockPublicPolicy: true
        IgnorePublicAcls: true
        RestrictPublicBuckets: true

  BudgetAmountParameter:
    Type: AWS::SSM::Parameter
    Properties:
      Name: !Ref BudgetParameterName
      Type: String
      Value: '10'
      Description: Monthly budget amount for AWS cost alerts.

Outputs:
  FunctionName:
    Description: Lambda function name
    Value: !Ref CostAlertFunction
  ScheduleExpression:
    Description: EventBridge schedule
    Value: !Ref ScheduleExpression
  ArchiveBucketName:
    Condition: UseArchive
    Description: S3 bucket for archives
    Value: !Ref ArchiveBucket
