AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31
Description: AWS Cost Alert System (SAM)

Parameters:
  ProjectName:
    Type: String
    Default: aws-cost-alerts
    Description: Base name used for resources.
  ScheduleExpression:
    Type: String
    Default: cron(0 8 * * ? *)
    Description: EventBridge schedule (defaults to 08:00 UTC daily).
  SenderEmail:
    Type: String
    Default: ''
    Description: SES-verified sender email (required for SES).
  RecipientEmails:
    Type: String
    Default: ''
    Description: Comma-separated recipient emails.
  EmailSubjectPrefix:
    Type: String
    Default: AWS Cost Alert
    Description: Prefix used for email subject lines.
  ArchiveEnabled:
    Type: String
    Default: 'true'
    AllowedValues:
      - 'true'
      - 'false'
    Description: Enable S3 archival of daily JSON snapshots.
  ArchiveRetentionDays:
    Type: Number
    Default: 30
    Description: Days to retain archived data in S3.
  BudgetParameterName:
    Type: String
    Default: /cost-alerts/budget-amount
    Description: SSM Parameter name holding the monthly budget amount.
  TopServicesCount:
    Type: Number
    Default: 10
    Description: Number of top services to include in the breakdown.
  TrendDays:
    Type: Number
    Default: 7
    Description: Number of days to include in the daily trend chart.
  AnomalyThresholdPercent:
    Type: Number
    Default: 30
    Description: Percent above 7-day average to flag daily anomaly.
  BudgetThresholds:
    Type: String
    Default: 50,75,90,100
    Description: Comma-separated budget thresholds to flag (percent).

Conditions:
  UseArchive: !Equals [!Ref ArchiveEnabled, 'true']

Globals:
  Function:
    Runtime: python3.14
    Timeout: 60
    MemorySize: 256
    Tracing: Active
    Environment:
      Variables:
        PROJECT_NAME: !Ref ProjectName
        SENDER_EMAIL: !Ref SenderEmail
        RECIPIENT_EMAILS: !Ref RecipientEmails
        EMAIL_SUBJECT_PREFIX: !Ref EmailSubjectPrefix
        ARCHIVE_ENABLED: !Ref ArchiveEnabled
        ARCHIVE_BUCKET: !If [UseArchive, !Ref ArchiveBucket, '']
        ARCHIVE_RETENTION_DAYS: !Ref ArchiveRetentionDays
        BUDGET_PARAM_NAME: !Ref BudgetParameterName
        TOP_SERVICES_COUNT: !Ref TopServicesCount
        TREND_DAYS: !Ref TrendDays
        ANOMALY_THRESHOLD_PERCENT: !Ref AnomalyThresholdPercent
        BUDGET_THRESHOLDS: !Ref BudgetThresholds

Resources:
  DailyLogGroup:
    Type: AWS::Logs::LogGroup
    Properties:
      LogGroupName: !Sub '/aws/lambda/${ProjectName}-daily'
      RetentionInDays: 14

  CostAlertFunction:
    Type: AWS::Serverless::Function
    DependsOn: DailyLogGroup
    Properties:
      FunctionName: !Sub '${ProjectName}-daily'
      CodeUri: src/
      Handler: handler.lambda_handler
      LoggingConfig:
        LogGroup: !Sub '/aws/lambda/${ProjectName}-daily'
      Policies:
        - AWSLambdaBasicExecutionRole
        - Statement:
            - Sid: CostExplorerRead
              Effect: Allow
              Action:
                - ce:GetCostAndUsage
                - ce:GetCostForecast
              Resource: '*'
            - Sid: ParameterRead
              Effect: Allow
              Action:
                - ssm:GetParameter
              Resource: !Sub 'arn:${AWS::Partition}:ssm:${AWS::Region}:${AWS::AccountId}:parameter${BudgetParameterName}'
            - Sid: SendSesEmail
              Effect: Allow
              Action:
                - ses:SendEmail
              Resource: !Sub 'arn:${AWS::Partition}:ses:${AWS::Region}:${AWS::AccountId}:identity/*'
            - !If
              - UseArchive
              - Sid: ArchiveWrite
                Effect: Allow
                Action:
                  - s3:PutObject
                Resource:
                  - !Sub 'arn:${AWS::Partition}:s3:::${ArchiveBucket}/*'
              - !Ref AWS::NoValue
      Events:
        DailySchedule:
          Type: Schedule
          Properties:
            Schedule: !Ref ScheduleExpression
            Name: !Sub '${ProjectName}-daily-schedule'
            Description: Daily AWS cost alert schedule
            Enabled: true

  MonitorLogGroup:
    Type: AWS::Logs::LogGroup
    Properties:
      LogGroupName: !Sub '/aws/lambda/${ProjectName}-monitor'
      RetentionInDays: 14

  CostMonitorFunction:
    Type: AWS::Serverless::Function
    DependsOn: MonitorLogGroup
    Properties:
      FunctionName: !Sub '${ProjectName}-monitor'
      CodeUri: src/
      Handler: cost_monitor.lambda_handler
      LoggingConfig:
        LogGroup: !Sub '/aws/lambda/${ProjectName}-monitor'
      Policies:
        - AWSLambdaBasicExecutionRole
        - Statement:
            - Sid: CostExplorerRead
              Effect: Allow
              Action:
                - ce:GetCostAndUsage
              Resource: '*'
            - Sid: ParameterReadWrite
              Effect: Allow
              Action:
                - ssm:GetParameter
                - ssm:PutParameter
              Resource:
                - !Sub 'arn:${AWS::Partition}:ssm:${AWS::Region}:${AWS::AccountId}:parameter${BudgetParameterName}'
                - !Sub 'arn:${AWS::Partition}:ssm:${AWS::Region}:${AWS::AccountId}:parameter/cost-alerts/last-alert-month'
            - Sid: SendSesEmail
              Effect: Allow
              Action:
                - ses:SendEmail
              Resource: !Sub 'arn:${AWS::Partition}:ses:${AWS::Region}:${AWS::AccountId}:identity/*'
      Events:
        MonitorSchedule:
          Type: Schedule
          Properties:
            Schedule: rate(12 hours)
            Name: !Sub '${ProjectName}-monitor-schedule'
            Description: Ad-hoc cost threshold monitor (every 12 hours)
            Enabled: true

  ArchiveBucket:
    Type: AWS::S3::Bucket
    Condition: UseArchive
    DeletionPolicy: Retain
    UpdateReplacePolicy: Retain
    Properties:
      LifecycleConfiguration:
        Rules:
          - Id: ExpireCostAlerts
            Status: Enabled
            ExpirationInDays: !Ref ArchiveRetentionDays
      BucketEncryption:
        ServerSideEncryptionConfiguration:
          - ServerSideEncryptionByDefault:
              SSEAlgorithm: AES256
      PublicAccessBlockConfiguration:
        BlockPublicAcls: true
        BlockPublicPolicy: true
        IgnorePublicAcls: true
        RestrictPublicBuckets: true


Outputs:
  FunctionName:
    Description: Lambda function name
    Value: !Ref CostAlertFunction
  MonitorFunctionName:
    Description: Cost monitor function name
    Value: !Ref CostMonitorFunction
  ScheduleExpression:
    Description: EventBridge schedule
    Value: !Ref ScheduleExpression
  ArchiveBucketName:
    Condition: UseArchive
    Description: S3 bucket for archives
    Value: !Ref ArchiveBucket
